apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jupyterhub-spawn-reflector-global
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log", "events", "secrets", "services", "configmaps", "persistentvolumeclaims", "serviceaccounts"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jupyterhub-spawn-binding-ml-workload
  namespace: ml-workload-ns
subjects:
- kind: ServiceAccount
  name: hub
  namespace: jhub
roleRef:
  kind: ClusterRole
  name: jupyterhub-spawn-reflector-global
  apiGroup: rbac.authorization.k8s.io